name = "Automata Survivia"
author = "Sylv (SylvKT)"
version = "0.4.0-pre.1+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b15119a3f78f0e3cabbfe85a108107e7ef338e955a04dedd84aa127070fd87be"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.11"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
